data_root: /storage/ice1/2/9/eliu354/Projects/Diffusion-Delta-Compute/data
models_root: /storage/ice1/2/9/eliu354/Projects/Diffusion-Delta-Compute/models
outputs_root: /storage/ice1/2/9/eliu354/Projects/Diffusion-Delta-Compute/reports

